### ISSUE TITLE
Specify a license

### ISSUE THREAD

**Issue by ifraixedes** [yasutakatou/mdiff#1]
Please could you add a license to this work?

Without a license, many people would move away because they don't know what are the terms of using the software nor about the source code.

Adding a license will clarify the conditions and increase the attraction of using your work.

Thanks in advance.

**Comment by yasutakatou** [comment]
Many thanks for your issue!
I got  1st issue ever.

I think, this tool used modules are copy left license of all.
So, I can select license, I think. I choice MIT license

Thank you your kindness.
